site_name: 算法面试大集
site_author: Buffalo
theme:
  name: material
  primary: teal
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: teal # 上方的
      accent: amber # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  features:
    - navigation.section
    - navigation.expand
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - math
  language: zh

extra_css:
  - styles/extra.css

extra_javascript:
  - styles/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 2-3

nav:
  - 数学:
      - 概率统计: math/probability.md
      - 线性代数: math/linear.md
      - 微积分与优化: math/calculus.md
  - 机器学习:
      - 机器学习中的数学: machine/math.md
      - 机器学习算法: machine/machinelearning.md
      - 机器学习教程: machine/tutorial.md



